"""Validate an incoming package and roll back managed installation paths on failure."""
import os
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

import yaml


def validate(package):
    for name, key in (('preset/preset.yml', 'preset'), ('extension/extension.yml', 'extension'),
                      ('workflow/workflow.yml', 'workflow')):
        data = yaml.safe_load((package / name).read_text())
        if not isinstance(data, dict) or not isinstance(data.get(key), dict) or not data[key].get('id'):
            raise ValueError('invalid incoming manifest: ' + name)
        for group in data.get('provides', {}).values():
            for item in group:
                if not (package / Path(name).parent / item['file']).is_file():
                    raise ValueError('missing package file: ' + item['file'])


def main():
    package, target = map(lambda s: Path(s).resolve(), sys.argv[1:3])
    validate(package)
    # CLI-managed paths are dot directories. Snapshot existing ones and track newly
    # created ones; this also works for integrations outside the common agent list.
    # .git is excluded; this installer never rewrites commits or repository config.
    paths = [p for p in target.iterdir() if p.name.startswith('.') and p.name != '.git']
    with tempfile.TemporaryDirectory(prefix='speckit-pro-install-') as tmp:
        backup = Path(tmp)
        for path in paths:
            if path.is_symlink(): raise ValueError('installation path is a symlink: ' + str(path))
            if path.is_dir(): shutil.copytree(path, backup / path.name)
            else: shutil.copy2(path, backup / path.name)
        # Root guidance is generated by some integrations; preserve it too.
        guidance = {p.name: p.read_bytes() for p in target.glob('*.md')}
        result = subprocess.run([str(package / 'install.sh'), *sys.argv[3:]],
                                env={**os.environ, 'SPECKIT_PRO_INSTALL_TRANSACTION': '1'})
        if result.returncode:
            for path in target.iterdir():
                if path.name.startswith('.') and path.name != '.git':
                    if path.is_dir() and not path.is_symlink(): shutil.rmtree(path)
                    else: path.unlink()
            for path in backup.iterdir():
                if path.is_dir(): shutil.copytree(path, target / path.name)
                else: shutil.copy2(path, target / path.name)
            for path in target.glob('*.md'):
                if path.name not in guidance: path.unlink()
            for name, data in guidance.items(): (target / name).write_bytes(data)
            print('speckit-pro installation failed; previous managed files restored', file=sys.stderr)
        return result.returncode


if __name__ == '__main__':
    try:
        sys.exit(main())
    except (OSError, ValueError, KeyError, TypeError, yaml.YAMLError) as exc:
        print('speckit-pro install validation failed: ' + str(exc), file=sys.stderr)
        sys.exit(1)
